In [1]:
import pandas
pandas.set_option("display.max_rows", None)

In [2]:
from src.compare import Compare

In [3]:
left_file = '../data/input_data/Березовская/24.ИА-23-003099.25.1-ЭТ2 20250424.csv'
right_file = '../data/input_data/Березовская/24.ИА-23-003099.25.1-ЭТ2 20250515.csv'
sort_array = [
    'ШКАФ',
    'Имя',
    'КЛЕММНИК',
    'УСТРОЙСТВО',
    'КЛЕММА',
]
columns = [
    'Имя',
    'ВН_ЖИЛА',
    'КЛЕММА',
    'УСТРОЙСТВО',
    'ШКАФ',
    'ЖИЛА',
    'КАБЕЛЬ',
    'КЛЕММНИК',
    'КАБЕЛЬ2',
    'ЖИЛА2',
    'ТИП',
    'Тип1',
    'СЕЧЕНИЕ',
    'ТИП_КАБЕЛЯ',
    'Слой',
    'ПРИМЕЧАНИЕ',
]

In [4]:
a = {
    'КЛЕММА_ВН1': ['КЛЕММА', 'ВН_ЖИЛА', 'УСТРОЙСТВО', 'ШКАФ', 'СЕЧЕНИЕ'],
    'КЛЕММА_ВН2': ['КЛЕММА', 'ВН_ЖИЛА', 'УСТРОЙСТВО', 'ШКАФ', 'СЕЧЕНИЕ'],
    'КЛЕММА1': ['КЛЕММА', 'ЖИЛА', 'ВН_ЖИЛА', 'КАБЕЛЬ', 'КЛЕММНИК', 'ШКАФ', 'ПРИМЕЧАНИЕ', 'СЕЧЕНИЕ', 'ТИП_КАБЕЛЯ'],
    'КЛЕММА2': ['КЛЕММА', 'ЖИЛА', 'ВН_ЖИЛА', 'КАБЕЛЬ', 'КЛЕММНИК', 'ШКАФ', 'ПРИМЕЧАНИЕ', 'СЕЧЕНИЕ', 'ТИП_КАБЕЛЯ'],
    'КЛЕММА1_2КАБ': ['КЛЕММА', 'ЖИЛА', 'ВН_ЖИЛА', 'КАБЕЛЬ', 'КЛЕММНИК', 'ШКАФ', 'КАБЕЛЬ2', 'ПРИМЕЧАНИЕ', 'СЕЧЕНИЕ', 'ТИП_КАБЕЛЯ'],
    'КЛЕММА2_2КАБ': ['КЛЕММА', 'ЖИЛА', 'ВН_ЖИЛА', 'КАБЕЛЬ', 'КЛЕММНИК', 'ШКАФ', 'КАБЕЛЬ2', 'ЖИЛА2', 'ПРИМЕЧАНИЕ', 'СЕЧЕНИЕ', 'ТИП_КАБЕЛЯ'],
    'Устройство': ['УСТРОЙСТВО', 'ШКАФ', 'ТИП', 'ПРИМЕЧАНИЕ'],
}

In [5]:
merge = Compare(left_file, right_file, sort_array, columns, lambda x: '+' if x == right_file else '-')
diff = merge.diff()

In [6]:
merge.select_columns('КЛЕММА_ВН2', a)

    _merge КЛЕММА ВН_ЖИЛА УСТРОЙСТВО ШКАФ СЕЧЕНИЕ
3        -     44     391       KLC1   06    0.75
4        +     44   391-2       KLC1   06    0.75
5        -     13     393       KLR1   06    0.75
6        +     13   393-2       KLR1   06    0.75
7        -      A     391       KLR1   06    0.75
8        +      A   391-2       KLR1   06    0.75
9        -     13    1397       KLR2   06    0.75
10       +     13  1397-2       KLR2   06    0.75
11       -     44     393       KLT1   06    0.75
12       +     44   393-2       KLT1   06    0.75
13       -     44    1397       KLT2   06    0.75
14       +     44  1397-2       KLT2   06    0.75
15       -      1    1504       KS10   06    0.75
16       +      1    2504       KS10   06    0.75
17       +     21    1504       KS10   06    0.75
18       +     22  1504-2       KS10   06    0.75
19       -     61    1504       KS10   06    0.75
20       -     62  1504-2       KS10   06    0.75
21       -     10    1510       KS11   06    0.75
22       +     10    2510       KS11   06    0.75
23       -      9    1504       KS11   06    0.75
24       +      9    2504       KS11   06    0.75
25       -      1    1510       KS20   06    0.75
26       +      1    2510       KS20   06    0.75
27       +     21    1510       KS20   06    0.75
28       +     22  1510-2       KS20   06    0.75
29       -     61    1510       KS20   06    0.75
30       -     62  1510-2       KS20   06    0.75
150      -      1       L        SF1   36    0.75
151      -      2      L1        SF1   36    0.75
152      -      +     G1+        SW1   36    0.75
153      -      -     G1-        SW1   36    0.75

In [7]:
merge.select_columns('КЛЕММА1', a)

,_merge,КЛЕММА,ЖИЛА,ВН_ЖИЛА,КАБЕЛЬ,КЛЕММНИК,ШКАФ,ПРИМЕЧАНИЕ,СЕЧЕНИЕ,ТИП_КАБЕЛЯ
1,-,4,RJ45,SW2:4,#0413,SW2,04,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV
2,+,4,RJ45,SW3:4,#0413,SW3,04,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV
51,-,15,7703,7703,#0722,X2,07,,1.5,КВВГЭнг(A)-LS
52,+,15,7703,7703,#0723,X2,07,,1.5,КВВГЭнг(A)-LS
53,-,16,7704,7704,#0722,X2,07,,1.5,КВВГЭнг(A)-LS
54,+,16,7704,7704,#0723,X2,07,,1.5,КВВГЭнг(A)-LS
55,-,35,7803,7803,#0722,X2,07,,1.5,КВВГЭнг(A)-LS
56,+,35,7803,7803,#0723,X2,07,,1.5,КВВГЭнг(A)-LS
57,-,36,7804,7804,#0722,X2,07,,1.5,КВВГЭнг(A)-LS
58,+,36,7804,7804,#0723,X2,07,,1.5,КВВГЭнг(A)-LS
59,-,1,R,SW3:9-TX,#1336,KO1,13,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40
60,+,1,R,U1:SFP,#1336,KO1,13,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40
61,+,2,G,,#1336,KO1,13,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40
62,-,2,G,SW3:9-RX,#1336,KO1,13,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40
63,-,3,Y,SW3:10-TX,#1336,KO1.1,13,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40
64,+,3,Y,U2:SFP,#1336,KO1.1,13,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40
65,+,4,B,,#1336,KO1.1,13,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40
66,-,4,B,SW3:10-RX,#1336,KO1.1,13,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40
67,+,3,RJ45,SW2:3,#1324,SW2,13,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV
68,+,4,RJ45,SW2:4,#1324,SW2,13,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV
69,+,5,RJ45,SW2:5,#0413,SW2,13,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV
70,-,1,RJ45,SW3:1,#0413,SW3,13,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV
71,-,2,RJ45,SW3:2,#1324,SW3,13,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV
72,-,3,RJ45,SW3:3,#1324,SW3,13,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV
73,-,4,,,,SW3,13,,0.6,STP-4P-Cat.6a-SOLID-IN-LSZH
92,-,25,6055,6055,#0119,X2,19,,1.5,КВВГЭнг(A)-LS
93,+,25,6055,6055,#0119,X2,19,+Uип (24V),1.5,КВВГЭнг(A)-LS
94,-,26,6056,6056,#0119,X2,19,Ток ротора ТГ1,1.5,КВВГЭнг(A)-LS
95,+,26,6056,6056,#0119,X2,19,Ток ротора ТГ1 (If.g),1.5,КВВГЭнг(A)-LS
96,-,27,6057,6057,#0119,X2,19,,1.5,КВВГЭнг(A)-LS
97,+,27,6057,6057,#0119,X2,19,-Uип (24V),1.5,КВВГЭнг(A)-LS
99,-,A,7203,7203,#0722,XA033,22,10MKF30CT001B\PТемпература охл. ТП на входе ка...,1.5,КВВГЭнг(A)-LS
100,-,B,7204,7204,#0722,XA033,22,10MKF30CT001B\PТемпература охл. ТП на входе ка...,1.5,КВВГЭнг(A)-LS
101,-,C,7403,7403,#0722,XA033,22,10MKF30CT002B\PТемпература охл. ТП на выходе к...,1.5,КВВГЭнг(A)-LS
102,-,D,7404,7404,#0722,XA033,22,10MKF30CT002B\PТемпература охл. ТП на выходе к...,1.5,КВВГЭнг(A)-LS
103,+,E,6103,,#1122,XA033,22,10BBB03CE002\PТок ротора ВГ,1.5,КВВГЭнг(A)-LS
104,-,E,8041,,#0622,XA033,22,10BBB03CE002\PНапряжение\Pстатора ВГ,1.5,КВВГЭнг(A)-LS
105,+,F,6104,,#1122,XA033,22,10BBB03CE002\PТок ротора ВГ,1.5,КВВГЭнг(A)-LS
106,-,F,8042,,#0622,XA033,22,10BBB03CE002\PНапряжение\Pстатора ВГ,1.5,КВВГЭнг(A)-LS
107,-,G,6103,,#1122,XA033,22,10BBB03CE003\PТок ротора ВГ,1.5,КВВГЭнг(A)-LS
108,+,G,8041,,#0622,XA033,22,10BBB03CE003\PНапряжение\Pстатора ВГ,1.5,КВВГЭнг(A)-LS
109,-,H,6104,,#1122,XA033,22,10BBB03CE003\PТок ротора ВГ,1.5,КВВГЭнг(A)-LS
110,+,H,8042,,#0622,XA033,22,10BBB03CE003\PНапряжение\Pстатора ВГ,1.5,КВВГЭнг(A)-LS
111,-,E,7103,7103,#0722,XA034,22,10MKF30CT001A\PТемпература охл. ТП на входе ка...,1.5,КВВГЭнг(A)-LS
112,-,F,7104,7104,#0722,XA034,22,10MKF30CT001A\PТемпература охл. ТП на входе ка...,1.5,КВВГЭнг(A)-LS
113,-,G,7303,7303,#0722,XA034,22,10MKF30CT002A\PТемпература охл. ТП на выходе к...,1.5,КВВГЭнг(A)-LS
114,-,H,7304,7304,#0722,XA034,22,10MKF30CT002A\PТемпература охл. ТП на выходе к...,1.5,КВВГЭнг(A)-LS
115,-,C,7703,7703,#0722,XA040,22,10MKF30CF001A\PРасход охл. ТП на выходе канал 1,1.5,КВВГЭнг(A)-LS
116,-,D,7704,7704,#0722,XA040,22,10MKF30CF001A\PРасход охл. ТП на выходе канал 1,1.5,КВВГЭнг(A)-LS
117,-,E,7803,7803,#0722,XA040,22,10MKF30CF001B\PРасход охл. ТП на выходе канал 2,1.5,КВВГЭнг(A)-LS
118,-,F,7804,7804,#0722,XA040,22,10MKF30CF001B\PРасход охл. ТП на выходе канал 2,1.5,КВВГЭнг(A)-LS
119,-,I,6203,6203,#2022,XA040,22,10MKC10CE002\PНапряжение рез.\Pвозбуждения,1.5,КВВГЭнг(A)-LS
120,-,J,6204,6204,#2022,XA040,22,10MKC10CE002\PНапряжение рез.\Pвозбуждения,1.5,КВВГЭнг(A)-LS
121,+,E,6203,6203,#2022,XA046,22,10MKC10CE001\PНапряжение рез.\Pвозбуждения,1.5,КВВГЭнг(A)-LS
122,+,F,6204,6204,#2022,XA046,22,10MKC10CE001\PНапряжение рез.\Pвозбуждения,1.5,КВВГЭнг(A)-LS
123,+,A,7103,7103,#0722,XA07,22,10MKF30CT001\PТемпература охл. ТП на входе кан...,1.5,КВВГЭнг(A)-LS
124,+,B,7104,7104,#0722,XA07,22,10MKF30CT001\PТемпература охл. ТП на входе кан...,1.5,КВВГЭнг(A)-LS
125,+,C,7203,7203,#0722,XA07,22,10MKF30CT002\PТемпература охл. ТП на входе кан...,1.5,КВВГЭнг(A)-LS
126,+,D,7204,7204,#0722,XA07,22,10MKF30CT002\PТемпература охл. ТП на входе кан...,1.5,КВВГЭнг(A)-LS
127,+,E,7303,7303,#0722,XA07,22,10MKF31CT001\PТемпература охл. ТП на выходе ка...,1.5,КВВГЭнг(A)-LS
128,+,F,7304,7304,#0722,XA07,22,10MKF31CT001\PТемпература охл. ТП на выходе ка...,1.5,КВВГЭнг(A)-LS
129,+,G,7403,7403,#0722,XA07,22,10MKF31CT002\PТемпература охл. ТП на выходе ка...,1.5,КВВГЭнг(A)-LS
130,+,H,7404,7404,#0722,XA07,22,10MKF31CT002\PТемпература охл. ТП на выходе ка...,1.5,КВВГЭнг(A)-LS
131,+,11,7703,7703,#0723,X1.09,23,10MKF30CF001A\PРасход охл. ТП на выходе канал 1,1.5,КВВГЭнг(A)-LS
132,+,12,7704,7704,#0723,X1.09,23,10MKF30CF001A\PРасход охл. ТП на выходе канал 1,1.5,КВВГЭнг(A)-LS
133,+,3,7803,7803,#0723,X1.09,23,10MKF30CF001B\PРасход охл. ТП на выходе канал 2,1.5,КВВГЭнг(A)-LS
134,+,4,7804,7804,#0723,X1.09,23,10MKF30CF001B\PРасход охл. ТП на выходе канал 2,1.5,КВВГЭнг(A)-LS
135,-,1,R,SW1:9-RX,#1336,KO1,36,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40
136,+,1,R,SW1:9-RX,#1336,KO1,36,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40
137,-,2,G,SW1:9-TX,#1336,KO1,36,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40
138,+,2,G,SW1:9-TX,#1336,KO1,36,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40
139,-,3,Y,SW1:10-RX,#1336,KO1,36,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40
140,+,3,Y,SW1:10-RX,#1336,KO1,36,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40
141,-,4,B,SW1:10-TX,#1336,KO1,36,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40
142,+,4,B,SW1:10-TX,#1336,KO1,36,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40
143,-,1,RJ45,SW1:1,#3637,SW1,36,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV
144,-,1,L,L,,X1,36,,1.5,КВВГЭнг(A)-LS
145,-,2,N,N,,X1,36,,1.5,КВВГЭнг(A)-LS
174,-,1,RJ45,FW1:1,#3637,FW1,37,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV

In [8]:
diff

,Имя,ВН_ЖИЛА,КЛЕММА,УСТРОЙСТВО,ШКАФ,ЖИЛА,КАБЕЛЬ,КЛЕММНИК,КАБЕЛЬ2,ЖИЛА2,ТИП,Тип1,СЕЧЕНИЕ,ТИП_КАБЕЛЯ,Слой,ПРИМЕЧАНИЕ,_merge
1,КЛЕММА1,SW2:4,4,,04,RJ45,#0413,SW2,,,,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV,0,,-
2,КЛЕММА1,SW3:4,4,,04,RJ45,#0413,SW3,,,,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV,0,,+
3,КЛЕММА_ВН2,391,44,KLC1,06,,,,,,,,0.75,,0,,-
4,КЛЕММА_ВН2,391-2,44,KLC1,06,,,,,,,,0.75,,0,,+
5,КЛЕММА_ВН2,393,13,KLR1,06,,,,,,,,0.75,,0,,-
6,КЛЕММА_ВН2,393-2,13,KLR1,06,,,,,,,,0.75,,0,,+
7,КЛЕММА_ВН2,391,A,KLR1,06,,,,,,,,0.75,,0,,-
8,КЛЕММА_ВН2,391-2,A,KLR1,06,,,,,,,,0.75,,0,,+
9,КЛЕММА_ВН2,1397,13,KLR2,06,,,,,,,,0.75,,0,,-
10,КЛЕММА_ВН2,1397-2,13,KLR2,06,,,,,,,,0.75,,0,,+
11,КЛЕММА_ВН2,393,44,KLT1,06,,,,,,,,0.75,,0,,-
12,КЛЕММА_ВН2,393-2,44,KLT1,06,,,,,,,,0.75,,0,,+
13,КЛЕММА_ВН2,1397,44,KLT2,06,,,,,,,,0.75,,0,,-
14,КЛЕММА_ВН2,1397-2,44,KLT2,06,,,,,,,,0.75,,0,,+
15,КЛЕММА_ВН2,1504,1,KS10,06,,,,,,,,0.75,,0,,-
16,КЛЕММА_ВН2,2504,1,KS10,06,,,,,,,,0.75,,0,,+
17,КЛЕММА_ВН2,1504,21,KS10,06,,,,,,,,0.75,,0,,+
18,КЛЕММА_ВН2,1504-2,22,KS10,06,,,,,,,,0.75,,0,,+
19,КЛЕММА_ВН2,1504,61,KS10,06,,,,,,,,0.75,,0,,-
20,КЛЕММА_ВН2,1504-2,62,KS10,06,,,,,,,,0.75,,0,,-
21,КЛЕММА_ВН2,1510,10,KS11,06,,,,,,,,0.75,,0,,-
22,КЛЕММА_ВН2,2510,10,KS11,06,,,,,,,,0.75,,0,,+
23,КЛЕММА_ВН2,1504,9,KS11,06,,,,,,,,0.75,,0,,-
24,КЛЕММА_ВН2,2504,9,KS11,06,,,,,,,,0.75,,0,,+
25,КЛЕММА_ВН2,1510,1,KS20,06,,,,,,,,0.75,,0,,-
26,КЛЕММА_ВН2,2510,1,KS20,06,,,,,,,,0.75,,0,,+
27,КЛЕММА_ВН2,1510,21,KS20,06,,,,,,,,0.75,,0,,+
28,КЛЕММА_ВН2,1510-2,22,KS20,06,,,,,,,,0.75,,0,,+
29,КЛЕММА_ВН2,1510,61,KS20,06,,,,,,,,0.75,,0,,-
30,КЛЕММА_ВН2,1510-2,62,KS20,06,,,,,,,,0.75,,0,,-
31,Устройство,,,KS10,06,,,,,,ABB AF40-30-00-13,Катушка,,,0,Контактор,+
32,Устройство,,,KS10,06,,,,,,ABB AF40-30-00-13,НО,,,0,Контактор,+
33,Устройство,,,KS10,06,,,,,,ABB AF40-30-00-13,НО,,,0,Контактор,+
34,Устройство,,,KS10,06,,,,,,ABB AF40-30-00-13,НО,,,0,Контактор,+
35,Устройство,,,KS10,06,,,,,,ABB CA4-22E,НЗ,,,0,Блок-контакт фронтальный 2НО+2НЗ,+
36,Устройство,,,KS10,06,,,,,,OptiStart K-F-38-30-00-D220,Катушка,,,0,Контактор,-
37,Устройство,,,KS10,06,,,,,,OptiStart K-F-38-30-00-D220,НО,,,0,Контактор,-
38,Устройство,,,KS10,06,,,,,,OptiStart K-F-38-30-00-D220,НО,,,0,Контактор,-
39,Устройство,,,KS10,06,,,,,,OptiStart K-F-38-30-00-D220,НО,,,0,Контактор,-
40,Устройство,,,KS10,06,,,,,,OptiStart K-FX-48412,НЗ,,,0,Блок-контакт фронтальный 1НО+2НЗ,-
41,Устройство,,,KS20,06,,,,,,ABB AF40-30-00-13,Катушка,,,0,Контактор,+
42,Устройство,,,KS20,06,,,,,,ABB AF40-30-00-13,НО,,,0,Контактор,+
43,Устройство,,,KS20,06,,,,,,ABB AF40-30-00-13,НО,,,0,Контактор,+
44,Устройство,,,KS20,06,,,,,,ABB AF40-30-00-13,НО,,,0,Контактор,+
45,Устройство,,,KS20,06,,,,,,ABB CA4-22E,НЗ,,,0,Блок-контакт фронтальный 2НО+2НЗ,+
46,Устройство,,,KS20,06,,,,,,OptiStart K-F-38-30-00-D220,Катушка,,,0,Контактор,-
47,Устройство,,,KS20,06,,,,,,OptiStart K-F-38-30-00-D220,НО,,,0,Контактор,-
48,Устройство,,,KS20,06,,,,,,OptiStart K-F-38-30-00-D220,НО,,,0,Контактор,-
49,Устройство,,,KS20,06,,,,,,OptiStart K-F-38-30-00-D220,НО,,,0,Контактор,-
50,Устройство,,,KS20,06,,,,,,OptiStart K-FX-48412,НЗ,,,0,Блок-контакт фронтальный 1НО+2НЗ,-
51,КЛЕММА1,7703,15,,07,7703,#0722,X2,,,,,1.5,КВВГЭнг(A)-LS,0,,-
52,КЛЕММА1,7703,15,,07,7703,#0723,X2,,,,,1.5,КВВГЭнг(A)-LS,0,,+
53,КЛЕММА1,7704,16,,07,7704,#0722,X2,,,,,1.5,КВВГЭнг(A)-LS,0,,-
54,КЛЕММА1,7704,16,,07,7704,#0723,X2,,,,,1.5,КВВГЭнг(A)-LS,0,,+
55,КЛЕММА1,7803,35,,07,7803,#0722,X2,,,,,1.5,КВВГЭнг(A)-LS,0,,-
56,КЛЕММА1,7803,35,,07,7803,#0723,X2,,,,,1.5,КВВГЭнг(A)-LS,0,,+
57,КЛЕММА1,7804,36,,07,7804,#0722,X2,,,,,1.5,КВВГЭнг(A)-LS,0,,-
58,КЛЕММА1,7804,36,,07,7804,#0723,X2,,,,,1.5,КВВГЭнг(A)-LS,0,,+
59,КЛЕММА1,SW3:9-TX,1,,13,R,#1336,KO1,,,,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40,0,,-
60,КЛЕММА1,U1:SFP,1,,13,R,#1336,KO1,,,,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40,0,,+
61,КЛЕММА1,,2,,13,G,#1336,KO1,,,,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40,0,,+
62,КЛЕММА1,SW3:9-RX,2,,13,G,#1336,KO1,,,,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40,0,,-
63,КЛЕММА1,SW3:10-TX,3,,13,Y,#1336,KO1.1,,,,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40,0,,-
64,КЛЕММА1,U2:SFP,3,,13,Y,#1336,KO1.1,,,,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40,0,,+
65,КЛЕММА1,,4,,13,B,#1336,KO1.1,,,,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40,0,,+
66,КЛЕММА1,SW3:10-RX,4,,13,B,#1336,KO1.1,,,,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40,0,,-
67,КЛЕММА1,SW2:3,3,,13,RJ45,#1324,SW2,,,,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV,0,,+
68,КЛЕММА1,SW2:4,4,,13,RJ45,#1324,SW2,,,,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV,0,,+
69,КЛЕММА1,SW2:5,5,,13,RJ45,#0413,SW2,,,,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV,0,,+
70,КЛЕММА1,SW3:1,1,,13,RJ45,#0413,SW3,,,,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV,Смонтировать дополнительно,,-
71,КЛЕММА1,SW3:2,2,,13,RJ45,#1324,SW3,,,,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV,Смонтировать дополнительно,,-
72,КЛЕММА1,SW3:3,3,,13,RJ45,#1324,SW3,,,,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV,Смонтировать дополнительно,,-
73,КЛЕММА1,,4,,13,,,SW3,,,,,0.6,STP-4P-Cat.6a-SOLID-IN-LSZH,Смонтировать дополнительно,,-
74,Устройство,,,FJ1,13,,,,,,Cabeus simplex sc-st 9/125 sm 3м lszh FOP(s)-9...,Материал,,,Смонтировать дополнительно,Патч корд оптический,+
75,Устройство,,,FJ1,13,,,,,,Hyperline FC-D2-50-LC/PR-SC/PR-H-2M-LSZH-OR,Устройство,,,Смонтировать дополнительно,Патч корд оптический,-
76,Устройство,,,FJ2,13,,,,,,Cabeus simplex sc-st 9/125 sm 3м lszh FOP(s)-9...,Материал,,,Смонтировать дополнительно,Патч корд оптический,+
77,Устройство,,,FJ2,13,,,,,,Hyperline FC-D2-50-LC/PR-SC/PR-H-2M-LSZH-OR,Устройство,,,Смонтировать дополнительно,Патч корд оптический,-
78,Устройство,,,KO1,13,,,,,,W505-DIN-SC-8MM-8MMB-1,Устройство,,,Смонтировать дополнительно,Кросс оптический,-
79,Устройство,,,KO1,13,,,,,,W505-DIN-ST-8SM-8UPC,Устройство,,,Смонтировать дополнительно,Кросс оптический,+
80,Устройство,,,RJ1,13,,,,,,Cabeus PC-UTP-RJ45-Cat.5e-3m,Материал,,,Смонтировать дополнительно,Патч-корд медный,+
81,Устройство,,,RJ2,13,,,,,,Cabeus PC-UTP-RJ45-Cat.5e-3m,Материал,,,Смонтировать дополнительно,Патч-корд медный,+
82,Устройство,,,SFP1,13,,,,,,SNR-SFP-W35-3,Материал,,,Смонтировать дополнительно,SFP модуль,+
83,Устройство,,,SFP1,13,,,,,,НПП Русмодуль RSM1D1L055 850нм 550м,Материал,,,Defpoints,SFP модуль,-
84,Устройство,,,SFP2,13,,,,,,SNR-SFP-W35-3,Материал,,,Смонтировать дополнительно,SFP модуль,+
85,Устройство,,,SFP2,13,,,,,,НПП Русмодуль RSM1D1L055 850нм 550м,Материал,,,Defpoints,SFP модуль,-
86,Устройство,,,SW3,13,,,,,,Eltex MES3508,Устройство,,,Смонтировать дополнительно,Промышленный коммутатор,-
87,Устройство,,,U1,13,,,,,,SNR-CVT-1000SFP-V2,Устройство,,,Смонтировать дополнительно,Медиаконвертер,+
88,Устройство,,,U2,13,,,,,,SNR-CVT-1000SFP-V2,Устройство,,,Смонтировать дополнительно,Медиаконвертер,+
89,Устройство,,,XS1,13,,,,,,РД-47 240В на DIN-рейку PROxima EKF mds-47-pro,Материал,,,Defpoints,Розетка,+
90,Устройство,,,XS2,13,,,,,,РД-47 240В на DIN-рейку PROxima EKF mds-47-pro,Материал,,,Defpoints,Розетка,+
91,Устройство,,,Провод,13,,,,,,4 м,Материал,,,Defpoints,Провод ПУГВ 1x0.75,+
92,КЛЕММА1,6055,25,,19,6055,#0119,X2,,,,,1.5,КВВГЭнг(A)-LS,0,,-
93,КЛЕММА1,6055,25,,19,6055,#0119,X2,,,,,1.5,КВВГЭнг(A)-LS,0,+Uип (24V),+
94,КЛЕММА1,6056,26,,19,6056,#0119,X2,,,,,1.5,КВВГЭнг(A)-LS,0,Ток ротора ТГ1,-
95,КЛЕММА1,6056,26,,19,6056,#0119,X2,,,,,1.5,КВВГЭнг(A)-LS,0,Ток ротора ТГ1 (If.g),+
96,КЛЕММА1,6057,27,,19,6057,#0119,X2,,,,,1.5,КВВГЭнг(A)-LS,0,,-
97,КЛЕММА1,6057,27,,19,6057,#0119,X2,,,,,1.5,КВВГЭнг(A)-LS,0,-Uип (24V),+
98,Устройство,,,G1,19,,,,,,Mean Well MDR-60-24,Устройство,,,0,Блок питания,+
99,КЛЕММА1,7203,A,,22,7203,#0722,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT001B\PТемпература охл. ТП на входе ка...,-
100,КЛЕММА1,7204,B,,22,7204,#0722,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT001B\PТемпература охл. ТП на входе ка...,-
101,КЛЕММА1,7403,C,,22,7403,#0722,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT002B\PТемпература охл. ТП на выходе к...,-
102,КЛЕММА1,7404,D,,22,7404,#0722,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT002B\PТемпература охл. ТП на выходе к...,-
103,КЛЕММА1,,E,,22,6103,#1122,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10BBB03CE002\PТок ротора ВГ,+
104,КЛЕММА1,,E,,22,8041,#0622,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10BBB03CE002\PНапряжение\Pстатора ВГ,-
105,КЛЕММА1,,F,,22,6104,#1122,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10BBB03CE002\PТок ротора ВГ,+
106,КЛЕММА1,,F,,22,8042,#0622,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10BBB03CE002\PНапряжение\Pстатора ВГ,-
107,КЛЕММА1,,G,,22,6103,#1122,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10BBB03CE003\PТок ротора ВГ,-
108,КЛЕММА1,,G,,22,8041,#0622,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10BBB03CE003\PНапряжение\Pстатора ВГ,+
109,КЛЕММА1,,H,,22,6104,#1122,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10BBB03CE003\PТок ротора ВГ,-
110,КЛЕММА1,,H,,22,8042,#0622,XA033,,,,,1.5,КВВГЭнг(A)-LS,0,10BBB03CE003\PНапряжение\Pстатора ВГ,+
111,КЛЕММА1,7103,E,,22,7103,#0722,XA034,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT001A\PТемпература охл. ТП на входе ка...,-
112,КЛЕММА1,7104,F,,22,7104,#0722,XA034,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT001A\PТемпература охл. ТП на входе ка...,-
113,КЛЕММА1,7303,G,,22,7303,#0722,XA034,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT002A\PТемпература охл. ТП на выходе к...,-
114,КЛЕММА1,7304,H,,22,7304,#0722,XA034,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT002A\PТемпература охл. ТП на выходе к...,-
115,КЛЕММА1,7703,C,,22,7703,#0722,XA040,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CF001A\PРасход охл. ТП на выходе канал 1,-
116,КЛЕММА1,7704,D,,22,7704,#0722,XA040,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CF001A\PРасход охл. ТП на выходе канал 1,-
117,КЛЕММА1,7803,E,,22,7803,#0722,XA040,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CF001B\PРасход охл. ТП на выходе канал 2,-
118,КЛЕММА1,7804,F,,22,7804,#0722,XA040,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CF001B\PРасход охл. ТП на выходе канал 2,-
119,КЛЕММА1,6203,I,,22,6203,#2022,XA040,,,,,1.5,КВВГЭнг(A)-LS,0,10MKC10CE002\PНапряжение рез.\Pвозбуждения,-
120,КЛЕММА1,6204,J,,22,6204,#2022,XA040,,,,,1.5,КВВГЭнг(A)-LS,0,10MKC10CE002\PНапряжение рез.\Pвозбуждения,-
121,КЛЕММА1,6203,E,,22,6203,#2022,XA046,,,,,1.5,КВВГЭнг(A)-LS,0,10MKC10CE001\PНапряжение рез.\Pвозбуждения,+
122,КЛЕММА1,6204,F,,22,6204,#2022,XA046,,,,,1.5,КВВГЭнг(A)-LS,0,10MKC10CE001\PНапряжение рез.\Pвозбуждения,+
123,КЛЕММА1,7103,A,,22,7103,#0722,XA07,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT001\PТемпература охл. ТП на входе кан...,+
124,КЛЕММА1,7104,B,,22,7104,#0722,XA07,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT001\PТемпература охл. ТП на входе кан...,+
125,КЛЕММА1,7203,C,,22,7203,#0722,XA07,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT002\PТемпература охл. ТП на входе кан...,+
126,КЛЕММА1,7204,D,,22,7204,#0722,XA07,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CT002\PТемпература охл. ТП на входе кан...,+
127,КЛЕММА1,7303,E,,22,7303,#0722,XA07,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF31CT001\PТемпература охл. ТП на выходе ка...,+
128,КЛЕММА1,7304,F,,22,7304,#0722,XA07,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF31CT001\PТемпература охл. ТП на выходе ка...,+
129,КЛЕММА1,7403,G,,22,7403,#0722,XA07,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF31CT002\PТемпература охл. ТП на выходе ка...,+
130,КЛЕММА1,7404,H,,22,7404,#0722,XA07,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF31CT002\PТемпература охл. ТП на выходе ка...,+
131,КЛЕММА1,7703,11,,23,7703,#0723,X1.09,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CF001A\PРасход охл. ТП на выходе канал 1,+
132,КЛЕММА1,7704,12,,23,7704,#0723,X1.09,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CF001A\PРасход охл. ТП на выходе канал 1,+
133,КЛЕММА1,7803,3,,23,7803,#0723,X1.09,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CF001B\PРасход охл. ТП на выходе канал 2,+
134,КЛЕММА1,7804,4,,23,7804,#0723,X1.09,,,,,1.5,КВВГЭнг(A)-LS,0,10MKF30CF001B\PРасход охл. ТП на выходе канал 2,+
135,КЛЕММА1,SW1:9-RX,1,,36,R,#1336,KO1,,,,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40,0,,-
136,КЛЕММА1,SW1:9-RX,1,,36,R,#1336,KO1,,,,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40,0,,+
137,КЛЕММА1,SW1:9-TX,2,,36,G,#1336,KO1,,,,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40,0,,-
138,КЛЕММА1,SW1:9-TX,2,,36,G,#1336,KO1,,,,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40,0,,+
139,КЛЕММА1,SW1:10-RX,3,,36,Y,#1336,KO1,,,,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40,0,,-
140,КЛЕММА1,SW1:10-RX,3,,36,Y,#1336,KO1,,,,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40,0,,+
141,КЛЕММА1,SW1:10-TX,4,,36,B,#1336,KO1,,,,,0.125,TB-A-5-04T-E-K-LSZH-IN/OUT-40,0,,-
142,КЛЕММА1,SW1:10-TX,4,,36,B,#1336,KO1,,,,,0.125,TB-A-9-04T-E-K-LSZH-IN/OUT-40,0,,+
143,КЛЕММА1,SW1:1,1,,36,RJ45,#3637,SW1,,,,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV,0,,-
144,КЛЕММА1,L,1,,36,L,,X1,,,,,1.5,КВВГЭнг(A)-LS,0,,-
145,КЛЕММА1,N,2,,36,N,,X1,,,,,1.5,КВВГЭнг(A)-LS,0,,-
146,КЛЕММА_ВН1,L1,L,G1,36,,,,,,,,1.5,,0,,-
147,КЛЕММА_ВН1,N,N,G1,36,,,,,,,,1.5,,0,,-
148,КЛЕММА_ВН1,G1+,V+,G1,36,,,,,,,,1.5,,0,,-
149,КЛЕММА_ВН1,G1-,V-,G1,36,,,,,,,,1.5,,0,,-
150,КЛЕММА_ВН2,L,1,SF1,36,,,,,,,,0.75,,0,,-
151,КЛЕММА_ВН2,L1,2,SF1,36,,,,,,,,0.75,,0,,-
152,КЛЕММА_ВН2,G1+,+,SW1,36,,,,,,,,0.75,,0,,-
153,КЛЕММА_ВН2,G1-,-,SW1,36,,,,,,,,0.75,,0,,-
154,Устройство,,,FJ1,36,,,,,,Cabeus simplex sc-st 9/125 sm 3м lszh FOP(s)-9...,Материал,,,Смонтировать дополнительно,Патч корд оптический,+
155,Устройство,,,FJ1,36,,,,,,Hyperline FC-D2-50-LC/PR-SC/PR-H-2M-LSZH-OR,Материал,,,0,Патч корд оптический,-
156,Устройство,,,FJ2,36,,,,,,Cabeus simplex sc-st 9/125 sm 3м lszh FOP(s)-9...,Материал,,,Смонтировать дополнительно,Патч корд оптический,+
157,Устройство,,,FJ2,36,,,,,,Hyperline FC-D2-50-LC/PR-SC/PR-H-2M-LSZH-OR,Материал,,,0,Патч корд оптический,-
158,Устройство,,,G1,36,,,,,,Mean Well MDR-40-24,Устройство,,,0,Блок питания,-
159,Устройство,,,KO1,36,,,,,,W505-DIN-SC-8MM-8MMB-1,Устройство,,,0,Кросс оптический,-
160,Устройство,,,KO1,36,,,,,,Панель съемная ST(FC) 8 портов КРС,Материал,,,Defpoints,,+
161,Устройство,,,RJ1,36,,,,,,Cabeus PC-UTP-RJ45-Cat.5e-3m,Материал,,,Смонтировать дополнительно,Патч-корд медный,+
162,Устройство,,,RJ2,36,,,,,,Cabeus PC-UTP-RJ45-Cat.5e-3m,Материал,,,Смонтировать дополнительно,Патч-корд медный,+
163,Устройство,,,RJ45,36,,,,,,Hyperline RJ-45 8P8C,Материал,,,0,Разъем,-
164,Устройство,,,RJ45,36,,,,,,Hyperline RJ-45 8P8C,Материал,,,Смонтировать дополнительно,Разъем,-
165,Устройство,,,SF1,36,,,,,,OptiDin BM63-1C6-УХЛ3,Автомат,,,0,Выключатель автоматический,-
166,Устройство,,,SFP1,36,,,,,,SNR-SFP-W53-3,Материал,,,Смонтировать дополнительно,SFP модуль,+
167,Устройство,,,SFP1,36,,,,,,НПП Русмодуль RSM1D1L055 850нм 550м,Материал,,,Defpoints,SFP модуль,-
168,Устройство,,,SFP2,36,,,,,,SNR-SFP-W53-3,Материал,,,Смонтировать дополнительно,SFP модуль,+
169,Устройство,,,SFP2,36,,,,,,НПП Русмодуль RSM1D1L055 850нм 550м,Материал,,,Defpoints,SFP модуль,-
170,Устройство,,,SW1,36,,,,,,Eltex MES3508,Устройство,,,0,Промышленный коммутатор,-
171,Устройство,,,U1,36,,,,,,SNR-CVT-1000SFP-V2,Устройство,,,Смонтировать дополнительно,Медиаконвертер,+
172,Устройство,,,U2,36,,,,,,SNR-CVT-1000SFP-V2,Устройство,,,Смонтировать дополнительно,Медиаконвертер,+
173,Устройство,,,X1,36,,,,,,ДКС VPR-4-GY,Клеммник,,,0,Клемма проходная 4 кв.мм серая,-
174,КЛЕММА1,FW1:1,1,,37,RJ45,#3637,FW1,,,,,0.6,SFTP-4P-Cat.5e-SOLID-OUT-LSZH-UV,0,,-