In [1]:
import pandas
import shutil

from omegaconf import OmegaConf
from pathlib import Path
from os.path import basename
from datetime import datetime

In [2]:
unixtime = round(datetime.now().timestamp())

In [3]:
from src.station import config

In [4]:
project_config = config.load_config()

In [5]:
ekra_config = OmegaConf.load(project_config.project_dir / "config" / project_config.station / "ekra.yaml")

In [6]:
project_config = OmegaConf.merge(project_config, ekra_config)

In [7]:
output_dir = project_config.outp_dir
plot_dir = project_config.plot_dir
ekra_setpoint = project_config.EKRA_FILE
nrows_sp = project_config.EKRA_ROWS
ekra_skip_protection = project_config.EKRA_SKIP_PROTECTION

In [8]:
import src.plot_table as pl
from src.plot_table import fit_data

In [9]:
pandas.set_option("display.max_rows", None)

In [10]:
def replace_utf8(data_numpy):
    table_replace = {'Δ': 'd', '≡': 'm'}
    result = []
    for row in data_numpy:
        a = []
        for string in row:
            for what_replace, them_replace in table_replace.items():
                if string.find(what_replace) != -1:
                    string = string.replace(what_replace, them_replace)
            a.append(string)
        result.append(a)
    return result

def add_blank_line(data_numpy):
    result = []
    for i, row in enumerate(data_numpy):
        a = []
        if row[0] != '' and i != 0:
            result.append(len(row) * [''])
            print(f" ({row[0]})")
        for string in row:
            a.append(string)
        result.append(a)
    return result

def skip_protection(data_numpy):
    result = []
    skip = False
    for i, row in enumerate(data_numpy):
        a = []
        protection_name = row[0]
        if protection_name != '':  # Нашли начало уставок новой защиты
            skip = False
            for protection in ekra_skip_protection:  # Проверяем, нужно ли ее пропустить
                if protection_name.find(protection) != -1:
                    skip = True
                    break
            print(f'{"-" if skip else " "}[{protection_name}]: {i}')
        if skip == True:
            continue

        for string in row:
            a.append(string)
        result.append(a)
    return result

In [11]:
def plot_setpoints_protect(data_pandas, file_name):
    rows_in_first_sheet = 52
    rows_in_other_sheet = 62
    start_possition = {"X": 20, "Y": -13}
    table_width = [18, 15, 12, 10, 5, 5, 60, 20, 10, 15, 15]
    ksize_font = len(table_width) * [3.2 / 5]
    align = ["l", "c", "c", "c", "c", "l", "l", "l", "c", "c", "c"]
    if len(table_width) != len(align):
        raise Exception("Различное кол-во эл. в таблицах table_width и align")

    data_numpy = data_pandas.to_numpy()
    data_numpy = skip_protection(data_numpy)
    data_numpy = replace_utf8(data_numpy)
    data_numpy = add_blank_line(data_numpy)
    header_table = [list(range(1, len(table_width)+1))]

    pl.plot_split_table(
        fit_data(data_numpy, table_width, ksize_font=ksize_font, delim=" ", add_blank_line=False),
        header_table,
        table_width,
        rows_in_first_sheet,
        rows_in_other_sheet,
        start_possition,
        file_name,
        delta=25,
        align=align,
    )

    _ = shutil.copyfile(
        file_name, f"{output_dir}/{basename(file_name)[:-4]}-{unixtime}.lsp"
    )

In [12]:
usecols_sp = [5, 0, 1, 2, 3, 4, 6, 10, 11, 15, 16]
dtype=str

setpoint = pandas.read_excel(
    ekra_setpoint,
    skiprows=lambda x: True if x < 5 else False,
    sheet_name='Бланк уставок',
    keep_default_na=False,
    header=None,
    usecols=usecols_sp,
    nrows=nrows_sp,
    dtype=dtype,
)

In [13]:
plot_setpoints_protect(setpoint[usecols_sp], f'{plot_dir}/Схемы/РЗ. Уставки защит.lsp')

 [I Δ ВГ]: 0
 [I > ВГ]: 14
 [Iр < ВГ]: 17
 [Iр ВГ]: 23
 [Re < ВГ]: 55
 [Iр > ВГ]: 93
 [Iр > R ВГ]: 97
 [U > ВГ]: 101
 [U < ВГ]: 105
 [Iр > ИР ВГ]: 109
 [I > ТВ]: 112
 [ I >> ТВ]: 115
 [Iр ГГ]: 118
-[≡ Iр ГГ]: 152
 [Iр DC ГГ]: 201
 [Re < ГГ 1]: 236
 [Re < ГГ 2]: 271
-[Re < ГГ 3]: 306
 [Re < ГГ]: 341
 [Iр > ГГ]: 351
 [Iр DC > ГГ]: 358
 [Iр > R ГГ]: 366
 [Iр DC > R ГГ]: 373
 [I1 > ГГ]: 381
 [Iр < ГГ]: 383
 [Фi < ГГ]: 385
 [Q(P)]: 390
-[U > ГГ]: 445
-[U < ГГ (1)]: 452
-[U < ГГ (2)]: 454
 [F ГГ]: 456
 [Iр > ИР ГГ]: 468
 [РТ ГГ]: 471
 [Л1]: 473
 [Л2]: 474
 [Л3]: 476
 [Л8]: 479
 [Л9]: 480
 [Л11]: 481
 [С1]: 482
 [Л12]: 483
 (I > ВГ)
 (Iр < ВГ)
 (Iр ВГ)
 (Re < ВГ)
 (Iр > ВГ)
 (Iр > R ВГ)
 (U > ВГ)
 (U < ВГ)
 (Iр > ИР ВГ)
 (I > ТВ)
 ( I >> ТВ)
 (Iр ГГ)
 (Iр DC ГГ)
 (Re < ГГ 1)
 (Re < ГГ 2)
 (Re < ГГ)
 (Iр > ГГ)
 (Iр DC > ГГ)
 (Iр > R ГГ)
 (Iр DC > R ГГ)
 (I1 > ГГ)
 (Iр < ГГ)
 (Фi < ГГ)
 (Q(P))
 (F ГГ)
 (Iр > ИР ГГ)
 (РТ ГГ)
 (Л1)
 (Л2)
 (Л3)
 (Л8)
 (Л9)
 (Л11)
 (С1)
 (Л12)

In [14]:
pandas.set_option('display.max_columns', 25)

In [15]:
def plot_matrix_breaker(data_pandas, file_name):
    rows_in_first_sheet = 44
    rows_in_other_sheet = 64
    start_possition = {"X": 20, "Y": -350}
    table_width = [55, 50] + 20 * [4]
    ksize_font = len(table_width) * [3.2 / 5]
    align = ["l", "l"] + 20 * ["c"]
    if len(table_width) != len(align):
        raise Exception("Различное кол-во эл. в таблицах table_width и align")

    data_numpy = data_pandas.to_numpy()
    data_numpy = replace_utf8(data_numpy)
    header_table = [list(range(1, len(table_width)+1))]

    pl.plot_split_table(
        fit_data(data_numpy, table_width, ksize_font=ksize_font, delim=" ", add_blank_line=False),
        header_table,
        table_width,
        rows_in_first_sheet,
        rows_in_other_sheet,
        start_possition,
        file_name,
        delta=25,
        align=align,
    )

    _ = shutil.copyfile(
        file_name, f"{output_dir}/{basename(file_name)[:-4]}-{unixtime}.lsp"
    )

In [16]:
usecols_mb = list(range(2, 24))
matrix_breaker = pandas.read_excel(
    ekra_setpoint,
    sheet_name='Матрица',
    skiprows=4,
    header=None,
    usecols=usecols_mb,
    keep_default_na=False,
    dtype=str
)

In [17]:
plot_matrix_breaker(matrix_breaker, f'{plot_dir}/Схемы/РЗ. Матрица отключений.lsp')

In [18]:
matrix_breaker

,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
0,I Δ ВГ,Откл.,,+,+,,,,,,,,,,,,,,,,,+
1,I > ВГ,Сраб. (t),,+,+,,,,,,,,,,,,,,,,,+
2,Iр < ВГ,Сраб. (t1),,,,,,,,+,,,,,,,,,,,,
3,,Сраб. (t2),,+,+,,,,,,,,,,,,,,,,,+
4,Iр ВГ,Откл. (t1),,,,,,,,+,,+,,,,,,,,,,
5,,Откл. (t2),,,,,,,,,,,,,,,,,,,,
6,Iр > ВГ,Сраб. (t1),,,,,,,,+,,+,,,,,,,,,,
7,,Сраб. (t2),,+,+,,,,,,,,,,,,,,,,+,
8,Iр > R ВГ,Сраб. (t1),,,,,,,,+,,+,,,,,,,,,,
9,,Сраб. (t2),,+,+,,,,,,,,,,,,,,,,+,
10,U > ВГ,Сраб. (t),,+,+,,,,,,,,,,,,,,,,+,
11,U < ВГ,Сраб. (t),,+,+,,,,,,,,,,,,,,,,+,
12,Iр > ИР ВГ,Сраб. (t),,+,,,,,,,,,,,,,,,,,,
13,I > ТВ,Сраб. (t),,+,+,,,,,,,,,,,,,,,,+,
14,I >> ТВ,Сраб. (t),,+,+,,,,,,,,,,,,,,,,+,
15,Iр ГГ,Откл. (t1) при осн.СВ,,,,,,,,,+,,+,,,,,,,,,
16,,Откл. (t2) при осн.СВ,+,,+,,,,,,,,,,,,,,,,+,
17,,Откл. (t1) при рез.СВ,,,,,,,,,,,,,,,,,,,,
18,,Откл. (t2) при рез.СВ,+,,,+,,,,,,,,,,,,,,,+,
19,Re < ГГ,Откл. (t) при осн. СВ,,,,,,,,,,,,,,,,,,,,
20,,Откл. (t) при рез.1 СВ,,,,,,,,,,,,,,,,,,,,
21,,Откл. (t) при рез.2 СВ,,,,,,,,,,,,,,,,,,,,
22,Iр > ГГ,Сраб. (t1) при осн.СВ,,,,,,,,,+,,+,,,,,,,,,
23,,Сраб. (t2) при осн.СВ,+,,+,,,,,,,,,,,,,,,,+,
24,,Сраб. (t1) при рез.СВ,,,,,,,,,,,,,,,,,,,,
25,,Сраб. (t2) при рез.СВ,+,,,+,,,,,,,,,,,,,,,+,
26,Iр > R ГГ,Сраб. (t1) при осн.СВ,,,,,,,,,+,,+,,,,,,,,,
27,,Сраб. (t2) при осн.СВ,+,,+,,,,,,,,,,,,,,,,+,
28,,Сраб. (t1) при рез.СВ,,,,,,,,,,,,,,,,,,,,
29,,Сраб. (t2) при рез.СВ,+,,,+,,,,,,,,,,,,,,,+,
30,Q(P),Откл. (t1),,,,,,,,,+,,,,,,,,,,,
31,,Откл. (t2) при осн. СВ,,,,,,,,,,,,,,,,,,,,
32,,Откл. (t2) при рез. СВ,,,,,,,,,,,,,,,,,,,,
33,Фi < ГГ,Сраб. (t),,,,,,,,,,,,,,,,,,,,
34,,Разгрузка,,,,,,,,,,,,,,,,,,,,
35,,Действие Ip <,,,,,,,,,,,,,,,,,,,,
36,U > ГГ,Релейное развозб. (t),,,,,,,,,,,,,,,,,,,,
37,,Сраб. (t) при осн. СВ,,,,,,,,,,,,,,,,,,,,
38,,Сраб. (t) при рез. СВ,,,,,,,,,,,,,,,,,,,,
39,F ГГ,F< 1 ст.(t) при осн.СВ,,,,,,,,,,,,,,,,,,,,
40,,F< 1 ст.(t) при рез.СВ,,,,,,,,,,,,,,,,,,,,
41,,F< 2 ст.(t) при осн.СВ,,,,,,+,,,,,,,,,,,,,,
42,,F< 2 ст.(t) при рез.СВ,,,,,,,,,,,,,+,,,,,,,
43,Iр > ИР ГГ,Сраб. (t),,+,+,,,,,,,,,,,,,,,,+,
44,Приемные цепи,,,,,,,,,,,,,,,,,,,,,
45,Электрические защ. генератора,,,+,+,+,,,,,,,,,,,,,,,+,
46,Форсир.возб.ГГ при раб.с РВ,,,,,,,,,,,,,,,,,,,,,
47,Авария СТН (при раб.ГГ с осн.СВ),,,+,+,,,,,,,,,,,,,,,,+,
48,Отключение РВ (при раб. ГГ с РВ),,,,,,,,,,,,,,,,,,,,,
49,Технол.защ. (при раб.ГГ с осн.СВ),,,+,+,,,,,,,,,,,,,,,,+,
50,Технол.защ. (при раб.ГГ с РВ),,,,,+,,,,,,,,,,,,,,,+,
51,Защита ГГ при откл. возбужд.,,,,,,,,,,,,,,,,,,,,,
52,Снятие блокировки с ЗН,,,,,,,,,,,,,,,,,,,,,

In [19]:
setpoint[usecols_sp]

,5,0,1,2,3,4,6,10,11,15,16
0,I Δ ВГ,Iвг,2.652,5,А,ф,Начальный ток срабатывания,IСР.0,о.е.,0.2,0.2
1,,Iн вг,2.652,5,А,ф,Коэффициент торможения на первом наклонном уча...,КТ1,-,0.3,0.3
2,,,,,,,Коэффициент торможения на втором наклонном уча...,КТ2,-,0.3,0.3
3,,,,,,,Ток начала торможения первого наклонного участка,IНТ1,о.е.,0.8,0.67
4,,,,,,,Ток начала торможения второго наклонного участка,IНТ2,о.е.,1.2,2.2
5,,,,,,,Ток срабатывания дифференциальной отсечки,IОТС,о.е.,6,6
6,,,,,,,Количество токовых групп,NГР,-,2,2
7,,,,,,,Коэффициент фазовой коррекции (группа 1),KФ1,-,1,1
8,,,,,,,Коэффициент фазовой коррекции (группа 2),KФ2,-,1,-1
9,,,,,,,Коэффициент фазовой коррекции (группа 3),KФ3,-,1,
10,,,,,,,Коэффициент фазовой коррекции (группа 4),KФ4,-,1,
11,,,,,,,Коэффициент фазовой коррекции (группа 5),KФ5,-,1,
12,,,,,,,Начальный ток срабатывания при включении,IВКЛ,о.е.,0.2,0.2
13,,,,,,,Время загрубления защиты при включении,TВКЛ,с,0,0
14,I > ВГ,Iн вг,2.652,5,А,ф,Ток срабатывания,Iср,о.е.,5,2.3
15,,,,,,,Коэффициент возврата,Kвоз,-,0.95,0.95
16,,,,,,,Выдерка времени на срабатывание,Сраб_t,с,1,0.5
17,Iр < ВГ,Iтв_р,0.508,5,А,ф,Ток срабатывания,Iср,о.е.,5,0.2
18,,,,,,,Коэффициент возврата,Кв,-,1.05,1.05
19,,,,,,,"Ввод защиты с контролем (1 - по току, 0 - по п...",VXN1_Ip<ВГ,,1,0
20,,,,,,,Первая выдержка времени на срабатывание,Сраб_t1,с,1,0
21,,,,,,,Вторая выдержка времени на срабатывание,Сраб_t2,с,1.5,1
22,,,,,,,Выдержка времени на срабатывание для контроля ...,Ген_вкл_t,с,1,
23,Iр ВГ,Iтв_р,0.508,5,А,ф,Ток срабатывания сигнального органа,Iсигн,о.е.,1.5,1.1
24,,,,,,,Ток срабатывания пускового органа,Iпуск,о.е.,1.1,
25,,,,,,,Ток срабатывания органа отсечки,Iотс,о.е.,2,
26,,,,,,,Коэффициент уменьшения времени срабатывания ин...,К_ТдопИнт,-,1,
27,,,,,,,Минимальное время срабатывания,Tмин,с,1,
28,,,,,,,Максимальное время срабатывания,Tмакс,с,3600,
29,,,,,,,Время охлаждения,Tохл,с,100,
30,,,,,,,Коэффициент возврата сигнального органа,K_воз Сигн.,-,0.98,
31,,,,,,,Коэффициент возврата пускового органа,K_воз Пуск.,-,0.98,
32,,,,,,,Коэффициент возврата органа отсечки,K_воз Отс.,-,0.98,
33,,,,,,,Количество точек,Кол.тчк.,ед.,9,
34,,,,,,,Характеристика срабатывания,I1,о.е.,1.1,
35,,,,,,,,T1,с,3600,
36,,,,,,,,I2,о.е.,1.15,
37,,,,,,,,T2,с,900,
38,,,,,,,,I3,о.е.,1.2,
39,,,,,,,,T3,с,360,
40,,,,,,,,I4,о.е.,1.25,
41,,,,,,,,T4,с,300,
42,,,,,,,,I5,о.е.,1.3,
43,,,,,,,,T5,с,240,
44,,,,,,,,I6,о.е.,1.4,
45,,,,,,,,T6,с,180,
46,,,,,,,,I7,о.е.,1.5,
47,,,,,,,,T7,с,120,
48,,,,,,,,I8,о.е.,1.75,
49,,,,,,,,T8,с,90,
50,,,,,,,,I9,о.е.,2,
51,,,,,,,,T9,с,60,
52,,,,,,,Выдержка времени при срабатывании сигнального ...,Сигн_t,с,1,
53,,,,,,,Первая выдержка времени при срабатывании орган...,1,с,1,
54,,,,,,,Вторая выдержка времени при срабатывании орган...,2,с,1.5,
55,Re < ВГ,Uвых ВГ,,100,В,ф,Сопротивление срабатывания органа Сигн.,Rсраб1,кОм,12,20
56,,Uист ВГ,,100,В,ф,Сопротивление срабатывания органа Откл.,Rсраб2,кОм,6,6
57,,,,,,,Напряжение срабатывания органа контроля контак...,Pr,В,1,
58,,,,,,,Угол коррекции вектора Uвых,Fi,град,270,
59,,,,,,,Минимальная частота источника 17 Гц,Fмин,Гц,15,
60,,,,,,,Максимальная частота источника 17 Гц,Fмакс,Гц,19,
61,,,,,,,Коэффициент возврата сигнального органа,Kвоз.Rсраб1,-,1.05,
62,,,,,,,Коэффициент возврата отключающего органа,Kвоз.Rсраб2,-,1.05,
63,,,,,,,Коэффициент возврата органа контроля контакта ...,Kвоз.Рr,-,0.8,
64,,,,,,,Коэффициент возврата органа контроля напряжени...,Kвоз.Uгмин,-,1.05,
65,,,,,,,Минимальное сопротивление,Rмин,кОм,2,
66,,,,,,,Максимальное сопротивление,Rмакс,кОм,100,
67,,,,,,,Количество точек характеристики срабатывания,Nточек,-,9,
68,,,,,,,Характеристика срабатывания,U1,В,1.937,
69,,,,,,,,R1,кОм,101,
70,,,,,,,,U2,В,3.065,
71,,,,,,,,R2,кОм,65,
72,,,,,,,,U3,В,4.763,
73,,,,,,,,R3,кОм,42,
74,,,,,,,,U4,В,7.131,
75,,,,,,,,R4,кОм,28,
76,,,,,,,,U5,В,9.822,
77,,,,,,,,R5,кОм,20,
78,,,,,,,,U6,В,12.813,
79,,,,,,,,R6,кОм,15,
80,,,,,,,,U7,В,15.681,
81,,,,,,,,R7,кОм,12,
82,,,,,,,,U8,В,28,
83,,,,,,,,R8,кОм,6,
84,,,,,,,,U9,В,57.09,
85,,,,,,,,R9,кОм,2,
86,,,,,,,Период времени усреднения замера сопротивления,T_сгл_R,с,0,
87,,,,,,,Период времени усреднения замера частоты,T_сгл_f,с,0.68,
88,,,,,,,Ввод блокировки при снижении напряжения источн...,Блк_Uг,-,0,
89,,,,,,,Ввод сигнализации при повышении частоты источн...,Fmax вкл.,-,1,
90,,,,,,,Выдержка вр. на сигнал при неиспр. источника 1...,Неиспр_17Гц,с,1,
91,,,,,,,Выдержка времени при срабатывании органа Сигн.,Сигн_t,с,1,10
92,,,,,,,Выдержка времени на ввод Re < ВГ,Re<ВГ_Ввод,с,1.5,
93,Iр > ВГ,Iтв_р,0.508,5,А,ф,Ток срабатывания,Iср,о.е.,5,1.725
94,,,,,,,Коэффициент возврата,Kвоз,-,0.95,0.95
95,,,,,,,Первая выдержка времени на срабатывание,Сраб_t1,с,1,0.8
96,,,,,,,Вторая выдержка времени на срабатывание,Сраб_t2,с,1.5,1.5
97,Iр > R ВГ,Iтв_р,0.508,5,А,ф,Ток срабатывания,Iср,о.е.,5,1.425
98,,,,,,,Коэффициент возврата,Kвоз,-,0.95,0.95
99,,,,,,,Первая выдержка времени на срабатывание,Сраб_t1,с,1,14.5
100,,,,,,,Вторая выдержка времени на срабатывание,Сраб_t2,с,1.5,15
101,U > ВГ,"Uвг, Y",100,100,В,л,Напряжение срабатывания,Uср,о.е.,1,1.2
102,,,,,,,Коэффициент возврата,Квоз,-,0.95,0.95
103,,,,,,,"Ввод защиты с контролем (1 - по току, 0 - по п...",VXN1_U>ВГ,-,1,0
104,,,,,,,Выдержка времени на срабатывание,Сраб_t,с,1,3
105,U < ВГ,"Uвг, Y",0.508,100,В,л,Напряжение срабатывания,Uср,о.е.,1,0.6
106,,,,,,,Коэффициент возврата,Квоз,-,1.05,1.05
107,,,,,,,"Ввод защиты с контролем (1 - по току, 0 - по п...",VXN1_U<ВГ,-,1,0
108,,,,,,,Выдержка времени на срабатывание,Сраб_t,с,1,2.5
109,Iр > ИР ВГ,Iтв_р,0.508,5,А,ф,Ток срабатывания,Iср,о.е.,4.19,0.1
110,,,,,,,Коэффициент возврата,Kвоз,-,0.95,0.95
111,,,,,,,Выдержка времени на срабатывание,Сраб_t,с,1,1
112,I > ТВ,Iтв,0.613,5,А,ф,Ток срабатывания,Iср,о.е.,0.625,2.822
113,,,,,,,Коэффициент возврата,Kвоз,-,0.95,0.95
114,,,,,,,Выдержка времени на срабатывание,Сраб_t,с,1,0.5
115,I >> ТВ,Iтв,0.613,5,А,ф,Ток срабатывания,Iср,о.е.,0.625,25.3
116,,,,,,,Коэффициент возврата,Kвоз,-,0.95,0.95
117,,,,,,,Выдержка времени на срабатывание,Сраб_t,с,1,0.01
118,Iр ГГ,Iн вг_р,2.62,5,А,ф,Ток срабатывания сигнального органа,Iсигн,о.е.,1.05,1.05
119,,,,,,,Ток срабатывания пускового органа,Iпуск,о.е.,1.1,1.06
120,,,,,,,Ток срабатывания органа отсечки,Iотс,о.е.,2,3
121,,,,,,,Коэффициент уменьшения времени срабатывания ин...,К_ТдопИнт,-,1,
122,,,,,,,Минимальное время срабатывания,Tмин,с,1,1
123,,,,,,,Максимальное время срабатывания,Tмакс,с,3600,3600
124,,,,,,,Время охлаждения,Tохл,с,100,1200
125,,,,,,,Коэффициент возврата сигнального органа,K_воз Сигн.,-,0.98,
126,,,,,,,Коэффициент возврата пускового органа,K_воз Пуск.,-,0.98,
127,,,,,,,Коэффициент возврата органа отсечки,K_воз Отс.,-,0.98,
128,,,,,,,Количество точек,Кол.тчк.,ед.,9,5
129,,,,,,,Характеристика срабатывания,I1,о.е.,1.1,1.06
130,,,,,,,,T1,с,3600,3600
131,,,,,,,,I2,о.е.,1.15,1.1
132,,,,,,,,T2,с,900,500
133,,,,,,,,I3,о.е.,1.2,1.2
134,,,,,,,,T3,с,360,180
135,,,,,,,,I4,о.е.,1.25,1.5
136,,,,,,,,T4,с,300,45
137,,,,,,,,I5,о.е.,1.3,2
138,,,,,,,,T5,с,240,15
139,,,,,,,,I6,о.е.,1.4,
140,,,,,,,,T6,с,180,
141,,,,,,,,I7,о.е.,1.5,
142,,,,,,,,T7,с,120,
143,,,,,,,,I8,о.е.,1.75,
144,,,,,,,,T8,с,90,
145,,,,,,,,I9,о.е.,2,
146,,,,,,,,T9,с,60,
147,,,,,,,Выдержка времени при срабатывании сигнального ...,Сигн_t,с,1,9
148,,,,,,,Первая выдержка времени при сраб. органа Откл....,Откл_t1_осн,с,1,0
149,,,,,,,Вторая выдержка времени при сраб. органа Откл....,Откл_t2_осн,с,1.5,1
150,,,,,,,Первая выдержка времени при сраб. органа Откл....,Откл_t1_рез,с,1,0
151,,,,,,,Вторая выдержка времени при сраб. органа Откл....,Откл_t2_рез,с,1.5,1
152,≡ Iр ГГ,Iгг,3.567,5,А,ф,Ток срабатывания сигнального органа,Iсигн,о.е.,1.05,
153,,"Uгг, Y",57.735,100,В,ф,Ток срабатывания пускового органа,Iпуск,о.е.,1.1,
154,,,,,,,Ток срабатывания органа отсечки,Iотс,о.е.,2,
155,,,,,,,Коэффициент уменьшения времени срабатывания ин...,К_ТдопИнт,-,1,
156,,,,,,,Минимальное время срабатывания,Tмин,с,1,
157,,,,,,,Максимальное время срабатывания,Tмакс,с,3600,
158,,,,,,,Время охлаждения,Tохл,с,100,
159,,,,,,,Коэффициент возврата сигнального органа,K_воз Сигн.,-,0.98,
160,,,,,,,Коэффициент возврата пускового органа,K_воз Пуск.,-,0.98,
161,,,,,,,Коэффициент возврата органа отсечки,K_воз Отс.,-,0.98,
162,,,,,,,Количество точек,Nточек,ед.,9,
163,,,,,,,Характеристика срабатывания,I1,о.е.,1.1,
164,,,,,,,,T1,с,3600,
165,,,,,,,,I2,о.е.,1.15,
166,,,,,,,,T2,с,900,
167,,,,,,,,I3,о.е.,1.2,
168,,,,,,,,T3,с,360,
169,,,,,,,,I4,о.е.,1.25,
170,,,,,,,,T4,с,300,
171,,,,,,,,I5,о.е.,1.3,
172,,,,,,,,T5,с,240,
173,,,,,,,,I6,о.е.,1.4,
174,,,,,,,,T6,с,180,
175,,,,,,,,I7,о.е.,1.5,
176,,,,,,,,T7,с,120,
177,,,,,,,,I8,о.е.,1.75,
178,,,,,,,,T8,с,90,
179,,,,,,,,I9,о.е.,2,
180,,,,,,,,T9,с,60,
181,,,,,,,Сопротивление Потье,Xp,о.е.,0.162,
182,,,,,,,Количество точек характеристики холостого хода,Nточек_ПТР,ед.,8,
183,,,,,,,Характеристика холостого хода,U1,о.е.,0.32,
184,,,,,,,,I1,о.е.,0.1,
185,,,,,,,,U2,о.е.,0.5,
186,,,,,,,,I2,о.е.,0.15,
187,,,,,,,,U3,о.е.,0.56,
188,,,,,,,,I3,о.е.,0.18,
189,,,,,,,,U4,о.е.,0.67,
190,,,,,,,,I4,о.е.,0.21,
191,,,,,,,,U5,о.е.,0.88,
192,,,,,,,,I5,о.е.,0.28,
193,,,,,,,,U6,о.е.,0.97,
194,,,,,,,,I6,о.е.,0.32,
195,,,,,,,,U7,о.е.,1.05,
196,,,,,,,,I7,о.е.,0.36,
197,,,,,,,,U8,о.е.,1.16,
198,,,,,,,,I8,о.е.,0.45,
199,,,,,,,Ток ротора характеристики КЗ (для определения ...,Ip кз,о.е.,0.72,
200,,,,,,,Ток статора характеристики КЗ (для определения...,Iс кз,о.е.,1,
201,Iр DC ГГ,Iр,9.133,,мА,ф,Номинальный ток ротора,Iр.ном,А,2900,3850
202,,,,,,,Ток срабатывания сигнального органа,Iсигн,о.е.,1.1,1.05
203,,,,,,,Ток срабатывания пускового органа,Iпуск,о.е.,1.1,1.06
204,,,,,,,Ток срабатывания органа отсечки,Iотс,о.е.,2,3
205,,,,,,,Коэффициент уменьшения времени срабатывания ин...,К_ТдопИнт,-,0.95,
206,,,,,,,Коэффициент возврата сигнального органа,K_воз Сигн.,-,0.98,
207,,,,,,,Коэффициент возврата пускового органа,K_воз Пуск.,-,0.98,
208,,,,,,,Коэффициент возврата органа отсечки,K_воз Отс.,-,0.98,
209,,,,,,,Минимальное время срабатывания,Tмин,с,1,
210,,,,,,,Максимальное время срабатывания,Tмакс,с,3600,
211,,,,,,,Время охлаждения,Tохл,с,100,
212,,,,,,,Количество точек,Кол.тчк.,ед.,9,5
213,,,,,,,Характеристика срабатывания,I1,о.е.,1.1,1.06
214,,,,,,,,T1,с,3600,3600
215,,,,,,,,I2,о.е.,1.15,1.1
216,,,,,,,,T2,с,900,500
217,,,,,,,,I3,о.е.,1.2,1.2
218,,,,,,,,T3,с,360,180
219,,,,,,,,I4,о.е.,1.25,1.5
220,,,,,,,,T4,с,300,45
221,,,,,,,,I5,о.е.,1.3,2
222,,,,,,,,T5,с,240,15
223,,,,,,,,I6,о.е.,1.4,
224,,,,,,,,T6,с,180,
225,,,,,,,,I7,о.е.,1.5,
226,,,,,,,,T7,с,120,
227,,,,,,,,I8,о.е.,1.75,
228,,,,,,,,T8,с,90,
229,,,,,,,,I9,о.е.,2,
230,,,,,,,,T9,с,60,
231,,,,,,,Минимальный выходной ток преобразователя тока ...,Iсм.дтр,мА,4,
232,,,,,,,Максимальный входной ток,Iвх.max,мА,25,21
233,,,,,,,Минимальный входной ток,Iвх.min,мА,4,3.7
234,,,,,,,Коэффициент возврата органа Iвх.max,K_воз.вх.max,-,0.95,
235,,,,,,,Коэффициент возврата органа Iвх.min,K_воз.вх.min,-,1.05,
236,Re < ГГ 1,Uвых ГГ,,,В,ф,Сопротивление срабатывания органа Сигн.,Rсраб1,кОм,12,6
237,,Uист ГГ,,,В,ф,Сопротивление срабатывания органа Откл.,Rсраб2,кОм,6,2.5
238,,,,,,,Напряжение срабатывания органа контроля контак...,Pr,В,2.2,
239,,,,,,,Угол коррекции вектора Uвых,Fi,град,229.1,
240,,,,,,,Минимальная частота источника 17 Гц,Fмин,Гц,15,
241,,,,,,,Максимальная частота источника 17 Гц,Fмакс,Гц,19,
242,,,,,,,Коэффициент возврата сигнального органа,Kвоз.Rсраб1,-,1.05,
243,,,,,,,Коэффициент возврата отключающего органа,Kвоз.Rсраб2,-,1.05,
244,,,,,,,Коэффициент возврата органа контроля контакта ...,Kвоз.Рr,-,1,
245,,,,,,,Коэффициент возврата органа контроля напряжени...,Kвоз.Uгмин,-,1.05,
246,,,,,,,Минимальное сопротивление,Rмин,кОм,2,
247,,,,,,,Максимальное сопротивление,Rмакс,кОм,100,
248,,,,,,,Количество точек характеристики срабатывания,Nточек,-,9,
249,,,,,,,Характеристика срабатывания,U1,В,1.939,
250,,,,,,,,R1,кОм,101,
251,,,,,,,,U2,В,3.082,
252,,,,,,,,R2,кОм,65,
253,,,,,,,,U3,В,4.802,
254,,,,,,,,R3,кОм,42,
255,,,,,,,,U4,В,7.131,
256,,,,,,,,R4,кОм,28,
257,,,,,,,,U5,В,9.876,
258,,,,,,,,R5,кОм,20,
259,,,,,,,,U6,В,12.921,
260,,,,,,,,R6,кОм,15,
261,,,,,,,,U7,В,15.753,
262,,,,,,,,R7,кОм,12,
263,,,,,,,,U8,В,28.141,
264,,,,,,,,R8,кОм,6,
265,,,,,,,,U9,В,58.26,
266,,,,,,,,R9,кОм,2,
267,,,,,,,Период времени усреднения замера сопротивления,T_сгл_R,с,0,
268,,,,,,,Период времени усреднения замера частоты,T_сгл_f,с,0.68,
269,,,,,,,Ввод блокировки при снижении напряжения источн...,Блк_Uг,-,0,
270,,,,,,,Ввод сигнализации при повышении частоты источн...,Fmax вкл.,-,1,
271,Re < ГГ 2,Uвых ГГ,,,В,ф,Сопротивление срабатывания органа Сигн.,Rсраб1,кОм,12,6
272,,Uист ГГ,,,В,ф,Сопротивление срабатывания органа Откл.,Rсраб2,кОм,6,2.5
273,,,,,,,Напряжение срабатывания органа контроля контак...,Pr,В,2.21,
274,,,,,,,Угол коррекции вектора Uвых,Fi,град,229.2,
275,,,,,,,Минимальная частота источника 17 Гц,Fмин,Гц,15,
276,,,,,,,Максимальная частота источника 17 Гц,Fмакс,Гц,19,
277,,,,,,,Коэффициент возврата сигнального органа,Kвоз.Rсраб1,-,1.05,
278,,,,,,,Коэффициент возврата отключающего органа,Kвоз.Rсраб2,-,1.05,
279,,,,,,,Коэффициент возврата органа контроля контакта ...,Kвоз.Рr,-,1,
280,,,,,,,Коэффициент возврата органа контроля напряжени...,Kвоз.Uгмин,-,1.05,
281,,,,,,,Минимальное сопротивление,Rмин,кОм,2,
282,,,,,,,Максимальное сопротивление,Rмакс,кОм,100,
283,,,,,,,Количество точек характеристики срабатывания,Nточек,-,9,
284,,,,,,,Характеристика срабатывания,U1,В,1.936,
285,,,,,,,,R1,кОм,101,
286,,,,,,,,U2,В,3.08,
287,,,,,,,,R2,кОм,65,
288,,,,,,,,U3,В,4.805,
289,,,,,,,,R3,кОм,42,
290,,,,,,,,U4,В,7.128,
291,,,,,,,,R4,кОм,28,
292,,,,,,,,U5,В,9.873,
293,,,,,,,,R5,кОм,20,
294,,,,,,,,U6,В,12.918,
295,,,,,,,,R6,кОм,15,
296,,,,,,,,U7,В,15.746,
297,,,,,,,,R7,кОм,12,
298,,,,,,,,U8,В,28.138,
299,,,,,,,,R8,кОм,6,
300,,,,,,,,U9,В,58.253,
301,,,,,,,,R9,кОм,2,
302,,,,,,,Период времени усреднения замера сопротивления,T_сгл_R,с,0,
303,,,,,,,Период времени усреднения замера частоты,T_сгл_f,с,0.68,
304,,,,,,,Ввод блокировки при снижении напряжения источн...,Блк_Uг,-,0,
305,,,,,,,Ввод сигнализации при повышении частоты источн...,Fmax вкл.,-,1,
306,Re < ГГ 3,Uвых ГГ,,,В,ф,Сопротивление срабатывания органа Сигн.,Rсраб1,кОм,12,
307,,Uист ГГ,,,В,ф,Сопротивление срабатывания органа Откл.,Rсраб2,кОм,6,
308,,,,,,,Напряжение срабатывания органа контроля контак...,Pr,В,2.2,
309,,,,,,,Угол коррекции вектора Uвых,Fi,град,229.3,
310,,,,,,,Минимальная частота источника 17 Гц,Fмин,Гц,15,
311,,,,,,,Максимальная частота источника 17 Гц,Fмакс,Гц,19,
312,,,,,,,Коэффициент возврата сигнального органа,Kвоз.Rсраб1,-,1.05,
313,,,,,,,Коэффициент возврата отключающего органа,Kвоз.Rсраб2,-,1.05,
314,,,,,,,Коэффициент возврата органа контроля контакта ...,Kвоз.Рr,-,1,
315,,,,,,,Коэффициент возврата органа контроля напряжени...,Kвоз.Uгмин,-,1.05,
316,,,,,,,Минимальное сопротивление,Rмин,кОм,2,
317,,,,,,,Максимальное сопротивление,Rмакс,кОм,100,
318,,,,,,,Количество точек характеристики срабатывания,Nточек,-,9,
319,,,,,,,Характеристика срабатывания,U1,В,1.941,
320,,,,,,,,R1,кОм,101,
321,,,,,,,,U2,В,3.082,
322,,,,,,,,R2,кОм,65,
323,,,,,,,,U3,В,4.806,
324,,,,,,,,R3,кОм,42,
325,,,,,,,,U4,В,7.132,
326,,,,,,,,R4,кОм,28,
327,,,,,,,,U5,В,9.875,
328,,,,,,,,R5,кОм,20,
329,,,,,,,,U6,В,12.921,
330,,,,,,,,R6,кОм,15,
331,,,,,,,,U7,В,15.753,
332,,,,,,,,R7,кОм,12,
333,,,,,,,,U8,В,28.142,
334,,,,,,,,R8,кОм,6,
335,,,,,,,,U9,В,58.263,
336,,,,,,,,R9,кОм,2,
337,,,,,,,Период времени усреднения замера сопротивления,T_сгл_R,с,0,
338,,,,,,,Период времени усреднения замера частоты,T_сгл_f,с,0.68,
339,,,,,,,Ввод блокировки при снижении напряжения источн...,Блк_Uг,-,0,
340,,,,,,,Ввод сигнализации при повышении частоты источн...,Fmax вкл.,-,1,
341,Re < ГГ,,,,,,Выдержка вр. на сигнал при неиспр. источника 1...,Неиспр_17Гц,с,1,
342,,,,,,,Выдержка времени при отскоке щетки,Отск_щетки_t,с,1,
343,,,,,,,Выдержка времени при срабатывании органа Сигн.,Сигн_t,с,1,9
344,,,,,,,Выдержка времени при срабатывании органа Откл....,Откл_t_осн,с,1,
345,,,,,,,Выдержка времени при срабатывании органа Откл....,Откл_t_рез1,с,1,
346,,,,,,,Выдержка времени при срабатывании органа Откл....,Откл_t_рез2,с,1,
347,,,,,,,Выдержка времени при неисправвности перевода СВ,Неиспр_пер_СВ,с,1,
348,,,,,,,Выдержка времени на ввод Re < ГГ 1,Re<ГГ_1_Ввод,с,1.5,0.5
349,,,,,,,Выдержка времени на ввод Re < ГГ 2,Re<ГГ_2_Ввод,с,1.5,0.5
350,,,,,,,Выдержка времени на ввод Re < ГГ 3,Re<ГГ_3_Ввод,с,1.5,0.5
351,Iр > ГГ,Iн вг_р,2.62,5,А,ф,Ток срабатывания,Iср,о.е.,3.945,2.3
352,,,,,,,Коэффициент возврата,Kвоз,-,0.95,0.95
353,,,,,,,Первая выдержка времени на срабатывание (осн.СВ),Сраб_t1_осн,с,1,0.8
354,,,,,,,Вторая выдержка времени на срабатывание (осн.СВ),Сраб_t2_осн,с,1.5,1.4
355,,,,,,,Первая выдержка времени на срабатывание (рез.СВ),Сраб_t1_рез,с,1,0.8
356,,,,,,,Вторая выдержка времени на срабатывание (рез.СВ),Сраб_t2_рез,с,1.5,1.4
357,,,,,,,Выдержка времени при неисправности Ip DC > ГГ,Нспр_IpDC>,с,1,
358,Iр DC > ГГ,Iр,9.133,5,мА,ф,Номинальный ток ротора,Iр.ном,А,2900,3850
359,,,,,,,Ток срабатывания,Iср,о.е.,1.1,2.3
360,,,,,,,Коэффициент возврата,Kвоз,-,0.95,0.95
361,,,,,,,Минимальный выходной ток преобразователя тока ...,Iсм.дтр,мА,4,4
362,,,,,,,Максимальный входной ток,Iвх.max,мА,25,21
363,,,,,,,Минимальный входной ток,Iвх.min,мА,4,3.7
364,,,,,,,Коэффициент возврата органа Iвх.max,K_воз.вх.max,с,0.95,0.95
365,,,,,,,Коэффициент возврата органа Iвх.min,K_воз.вх.min,с,1.05,1.05
366,Iр > R ГГ,Iн вг_р,2.62,5,А,ф,Ток срабатывания,Iср,о.е.,3.945,1.8
367,,,,,,,Коэффициент возврата,Kвоз,-,0.95,0.95
368,,,,,,,Первая выдержка времени на срабатывание (осн.СВ),Сраб_t1_осн,с,1,14
369,,,,,,,Вторая выдержка времени на срабатывание (осн.СВ),Сраб_t2_осн,с,1.5,15
370,,,,,,,Первая выдержка времени на срабатывание (рез.СВ),Сраб_t1_рез,с,1,14
371,,,,,,,Вторая выдержка времени на срабатывание (рез.СВ),Сраб_t2_рез,с,1.5,15
372,,,,,,,Выдержка времени при неисправности Ip DC > R ГГ,Нспр_IpDC>R,с,1,
373,Iр DC > R ГГ,Iр,9.133,5,мА,ф,Номинальный ток ротора,Iр.ном,А,2900,3850
374,,,,,,,Ток срабатывания,Iср,о.е.,1.1,1.8
375,,,,,,,Коэффициент возврата,Kвоз,-,0.95,0.95
376,,,,,,,Минимальный выходной ток преобразователя тока ...,Iсм.дтр,мА,4,4
377,,,,,,,Максимальный входной ток,Iвх.max,мА,25,21
378,,,,,,,Минимальный входной ток,Iвх.min,мА,4,3.7
379,,,,,,,Коэффициент возврата органа Iвх.max,K_воз.вх.max,с,0.95,0.95
380,,,,,,,Коэффициент возврата органа Iвх.min,K_воз.вх.min,с,1.05,1.05
381,I1 > ГГ,Iгг,3.567,5,А,ф,Ток срабатывания,Iср,о.е.,4.245,2
382,,,,,,,Коэффициент возврата,Кв,-,0.95,0.95
383,Iр < ГГ,Iн вг_р,2.62,5,А,ф,Ток срабатывания,Iср,о.е.,3.945,0.18
384,,,,,,,Коэффициент возврата,Кв,-,1.05,1.05
385,Фi < ГГ,,,,,,"Ввод защиты с контролем (1 - по току, 0 - по п...",VXN1_Фi<ГГ,-,1,0
386,,,,,,,Выдержка времени на срабатывание при включении...,Ген_вкл_t,с,1,
387,,,,,,,Первая выдержка времени на срабатывание,Ip<ГГ_t,с,1,
388,,,,,,,Вторая выдержка времени на срабатывание,Сраб_t,с,1.5,
389,,,,,,,Выдержка времени на срабатывание (дейст.на вкл...,Дейст_Ip<,с,1,
390,Q(P),Iгг,3.567,5,А,ф,Коэффициент мощности генератора,cos(Fi)ном,-,0.8,0.9
391,,"Uгг, Y",57.735,100,В,ф,Коэффициент возврата сигнального органа,K_воз Сигн.,-,0.95,0.95
392,,,,,,,Коэффициент возврата отключающего органа,K_воз Откл.,-,0.95,0.95
393,,,,,,,Перевод на модуль,0-P 1-|P|,-,0,
394,,,,,,,Максимальная велична активной мощности генератора,Pmax,о.е.,1.35,1.05
395,,,,,,,Минимальная велична активной мощности генератора,Pmin,о.е.,0,0
396,,,,,,,Количество точек характеристики,N,ед.,9,5
397,,,,,,,Характеристика срабатывания сигнального органа,P1_сигн,о.е.,0.15,0
398,,,,,,,,Q1_сигн,о.е.,-1.05,-0.95
399,,,,,,,,P2_сигн,о.е.,0.3,0.25
400,,,,,,,,Q2_сигн,о.е.,-1.05,-0.926
401,,,,,,,,P3_сигн,о.е.,0.45,0.625
402,,,,,,,,Q3_сигн,о.е.,-1.05,-0.828
403,,,,,,,,P4_сигн,о.е.,0.6,1
404,,,,,,,,Q4_сигн,о.е.,-1.05,-0.633
405,,,,,,,,P5_сигн,о.е.,0.75,1.025
406,,,,,,,,Q5_сигн,о.е.,-0.8,0
407,,,,,,,,P6_сигн,о.е.,0.9,
408,,,,,,,,Q6_сигн,о.е.,-0.6,
409,,,,,,,,P7_сигн,о.е.,1.05,
410,,,,,,,,Q7_сигн,о.е.,-0.4,
411,,,,,,,,P8_сигн,о.е.,1.2,
412,,,,,,,,Q8_сигн,о.е.,-0.1,
413,,,,,,,,P9_сигн,о.е.,1.35,